# You need to restart Redmine after modifying this file.
# These have to match with your Redmine setup, ie there must
# be a custom field for issues named "Release notes required"
# or whatever you changed it to.
# See the wiki on github for more details.

issue_required_field: "Release notes required"

field_value_done: "Yes - done"
field_value_to_be_done: "Yes - to be done"
field_value_not_required: "No - not applicable"

version_generated_field: "Release notes generated"

default_generation_format: "HTML"
