issue_required_field: "Release notes required"
version_generated_field: "Release notes generated"
field_value_done: "Yes - done"
field_value_to_be_done: "Yes - to be done"
field_value_not_required: "No - not applicable"
